config:
  debug: false
  detection area: 500
  display duration: true
  display optional windows: true
  gaussian blur: 0
  kernel size: 6
  rectangle color:
    blue: 0
    green: 255
    red: 0
  threshold: 70
